### ISSUE TITLE
npm install出错了

### ISSUE THREAD

**Issue by 1999zsh** [wzunjh/Library-Management-System#24]
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@3.19.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.nlark.com/y18n/download/y18n-5.0.8.tgz failed, reason: getaddrinfo ENOTFOUND registry.nlark.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by 1999zsh** [comment]
还有缺了一个echarts文件

**Comment by wzunjh** [comment]
你遇到了一些与 npm 相关的问题，主要有两部分：**过时的依赖警告** 和 **网络连接错误**。我们分别来看一下这些问题的原因及解决方案。

### 1. 过时的依赖警告

你收到了多个依赖包过时的警告，建议升级这些依赖。具体的警告信息如下：

1. **uuid@3.4.0**: 请升级到 7 版本或更高版本。旧版本在某些情况下可能使用 `Math.random()`，这已知存在问题。
2. **request@2.88.2**: request 包已被弃用。
3. **@hapi/hoek@8.5.1**: 该版本已不再维护。
4. **@hapi/joi@15.1.1**: 请切换到 `npm install joi`。
5. **svgo@1.3.2**: 请升级到 v2.x.x 版本。
6. **core-js@3.19.1**: core-js 3.23.3 以下的版本不再维护，并且不推荐使用。

#### 解决方案：
你可以运行以下命令来更新这些依赖：
```bash
npm install uuid@latest
npm install joi@latest
npm install svgo@latest
npm install core-js@latest
```
对于 `request` 包，你需要寻找替代方案，例如 `axios` 或 `node-fetch`。

### 2. 网络连接错误

你的 npm 在尝试连接 `https://registry.nlark.com/y18n/download/y18n-5.0.8.tgz` 时出现了 `ENOTFOUND` 错误。这通常是由于网络连接问题或配置问题导致的。

#### 可能原因及解决方法：

1. **网络连接问题**：
   - 确保你的网络连接正常，可以尝试访问其他网站，检查网络状态。
   - 重试安装命令，可能是临时的网络问题。

2. **代理配置问题**：
   - 如果你在使用代理，确保代理配置正确。可以通过以下命令配置 npm 代理：
     ```bash
     npm config set proxy http://your-proxy-server:port
     npm config set https-proxy http://your-proxy-server:port
     ```

3. **更改 npm 源**：
   - 如果问题持续，可以尝试更改 npm 源为官方源或其他国内源，如淘宝镜像。更改源的方法如下：
     ```bash
     npm config set registry https://registry.npmjs.org/
     ```
   或
     ```bash
     npm config set registry https://registry.npm.taobao.org/
     ```

4. **检查 DNS 设置**：
   - 由于错误信息中提到 `getaddrinfo ENOTFOUND`，这可能与 DNS 配置相关。你可以尝试更改 DNS 服务器，例如使用 Google 的 DNS 服务器（8.8.8.8 和 8.8.4.4）。

通过以上方法，你应该可以解决这些 npm 问题。如果问题仍然存在，请提供更多详细信息以便进一步排查。
